### ISSUE TITLE
Endpoint to calculate Salary

### ISSUE THREAD

**Issue by ighoshsubho** [Clueless-Community/fintech-api#203]
- The Salary Calculator converts salary amounts to their corresponding values based on payment frequency.
- Perform all the calculations in the `function.py` file present in helpers folder
- Create the endpoint `salary-calculate` in the `main.py` file and return the required result in a proper format

**Comment by Njoguu** [comment]
Hello @ighoshsubho, I noticed that the `diluted-earnings-per-share` endpoint takes in a payment frequency parameter, but it's not clear whether this parameter should be an integer (e.g. 1, 2, 3 month(s)) or a string (e.g. 'monthly', 'semi-annual', 'annual'). Can you please clarify this for me? Thank you!

**Comment by ighoshsubho** [comment]
It will be in strings like 'Hour', 'Day', 'Week', 'Month', and 'Year'. And sorry for the late response @Njoguu. I was a little busy with some other project. Should I assign you to this issue?

**Comment by Njoguu** [comment]
On it. One last issue, I'm a bit confused about the endpoint name and its functionality. The endpoint name (`diluted-earnings-per-share`) seems to be saying a different thing from what the endpoint is actually supposed to do (**convert the salary amounts based on payment frequency**), and I'm not sure if this is intentional or if there's been a misunderstanding somewhere. I would greatly appreciate it if you could help me better understand this endpoint and its intended functionality.

**Comment by ighoshsubho** [comment]
Oh sorry my bad, I was repeatedly getting this as a salary endpoint, make it `salary-calculate`, and refer to this -![Salary Calculate](https://www.calculator.net/salary-calculator.html), for your reference.
